# $OpenBSD$

COMMENT=	Vulkan header files

GH_TAGNAME=	sdk-${V}
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	Vulkan-Headers
V=		1.1.101.0
PKGNAME=	vulkan-headers-${V}

CATEGORIES=	devel graphics

HOMEPAGE=	https://www.khronos.org/vulkan/

# Apache 2.0
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	devel/cmake

.include <bsd.port.mk>
