# $OpenBSD$

COMMENT=	SPIRV-Headers

GH_TAGNAME=	${V}
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	SPIRV-Headers
V=		1.3.7
PKGNAME=	spirv-headers-${V}

CATEGORIES=	devel graphics

HOMEPAGE=	https://www.khronos.org/vulkan/

# Apache 2.0
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	devel/cmake

.include <bsd.port.mk>
