# $OpenBSD$

COMMENT=	reference front-end for GLSL and ESSL

GH_TAGNAME=	7.11.3113
GH_ACCOUNT=	KhronosGroup
GH_PROJECT=	glslang

CATEGORIES=	devel graphics

HOMEPAGE=	https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/

# Apache 2.0
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += ${COMPILER_LIBCXX} c m

MODULES=	devel/cmake

.include <bsd.port.mk>
